#!/bin/bash
# Regenerate format files using the WASM binary via Node.js.
# This ensures format files match the WASM engine's string pool.
#
# Run inside the emscripten container after install-tl has installed packages:
#   podman run --rm -v "$(pwd):/work" -w /work emscripten/emsdk:3.1.43 bash regen-formats.sh

set -e

TEXLIVE_DIR="build/texlive-basic"
WASM_DIR="build/wasm"
FMT_DIR="${TEXLIVE_DIR}/texmf-dist/texmf-var/web2c"

echo "=== Regenerating format files with WASM binary ==="
echo "Node version: $(node --version)"

# Remove old format files generated by native binary
echo "Removing old format files..."
rm -f ${FMT_DIR}/pdftex/*.fmt ${FMT_DIR}/xetex/*.fmt ${FMT_DIR}/luahbtex/*.fmt

# Create a Node.js script (CommonJS, no top-level await)
cat > /tmp/gen-format.js << 'SCRIPT'
'use strict';
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const engine = args[0];
const texliveDir = args[1];
const wasmDir = args[2];
const fmtOutputDir = args[3];

const engineMap = {
  'pdflatex':   { program: 'pdflatex',  iniArgs: ['-ini', '-jobname=pdflatex', '*pdflatex.ini'] },
  'xelatex':    { program: 'xelatex',   iniArgs: ['-ini', '-jobname=xelatex', '*xelatex.ini'] },
  'luahblatex': { program: 'luahblatex', iniArgs: ['-ini', '-jobname=lualatex', '*lualatex.ini'] },
};

const config = engineMap[engine];
if (!config) {
  console.error('Unknown engine: ' + engine);
  process.exit(1);
}

function collectFiles(dir, prefix) {
  var result = {};
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  for (var i = 0; i < entries.length; i++) {
    var entry = entries[i];
    var fullPath = path.join(dir, entry.name);
    var vfsPath = prefix ? prefix + '/' + entry.name : entry.name;
    if (entry.isDirectory()) {
      Object.assign(result, collectFiles(fullPath, vfsPath));
    } else if (entry.isFile()) {
      result[vfsPath] = fs.readFileSync(fullPath);
    }
  }
  return result;
}

async function main() {
  console.log('Generating format: ' + engine);

  var wasmBinary = fs.readFileSync(path.join(wasmDir, 'busytex.wasm'));

  console.log('Collecting texmf-dist files...');
  var texmfFiles = collectFiles(path.join(texliveDir, 'texmf-dist'), '/texlive/texmf-dist');
  console.log('Collected ' + Object.keys(texmfFiles).length + ' files');

  var busytexFactory = require(path.join(process.cwd(), wasmDir, 'busytex.js'));

  var Module = await busytexFactory({
    wasmBinary: wasmBinary,
    noInitialRun: true,
    thisProgram: '/texlive/texmf-dist/bin/busytex',
    arguments: [config.program].concat(config.iniArgs),
    preRun: [function(mod) {
      // Create a dummy binary so kpathsea can lstat it for $SELFAUTODIR
      mod.FS.mkdirTree('/texlive/texmf-dist/bin');
      mod.FS.writeFile('/texlive/texmf-dist/bin/busytex', '');
      var paths = Object.keys(texmfFiles);
      for (var i = 0; i < paths.length; i++) {
        var p = paths[i];
        var dir = path.dirname(p);
        try { mod.FS.mkdirTree(dir); } catch(e) {}
        mod.FS.writeFile(p, texmfFiles[p]);
      }
      mod.ENV['TEXMFCNF'] = '/texlive/texmf-dist/web2c';
    }],
    print: function(text) { console.log('[TeX] ' + text); },
    printErr: function(text) { console.error('[TeX ERR] ' + text); }
  });

  await Module.ready;

  try {
    Module.callMain([config.program].concat(config.iniArgs));
  } catch (e) {
    console.log('Engine exited: ' + e.message);
  }

  var fmtName = (engine === 'luahblatex' ? 'lualatex' : engine) + '.fmt';
  try {
    var fmtData = Module.FS.readFile(fmtName);
    fs.mkdirSync(fmtOutputDir, { recursive: true });
    var outputPath = path.join(fmtOutputDir, fmtName);
    fs.writeFileSync(outputPath, fmtData);
    console.log('Written: ' + outputPath + ' (' + fmtData.length + ' bytes)');
  } catch (e) {
    console.error('Failed to extract ' + fmtName + ': ' + e.message);
    try {
      console.log('CWD files:', Module.FS.readdir('.'));
    } catch(e2) {}
    process.exit(1);
  }
}

main().catch(function(e) { console.error(e); process.exit(1); });
SCRIPT

# Generate each format
for engine in pdflatex xelatex; do
  subdir=$(echo $engine | sed 's/pdflatex/pdftex/;s/xelatex/xetex/')
  mkdir -p "${FMT_DIR}/${subdir}"
  echo "--- Generating ${engine}.fmt ---"
  node /tmp/gen-format.js "$engine" "$TEXLIVE_DIR" "$WASM_DIR" "${FMT_DIR}/${subdir}" || echo "WARN: ${engine} format generation failed"
done

# Handle luahblatex separately (renamed from lualatex)
mkdir -p "${FMT_DIR}/luahbtex"
echo "--- Generating lualatex.fmt (for luahblatex) ---"
node /tmp/gen-format.js "luahblatex" "$TEXLIVE_DIR" "$WASM_DIR" "${FMT_DIR}/luahbtex" || echo "WARN: luahblatex format generation failed"

# Rename lualatex.fmt to luahblatex.fmt
if [ -f "${FMT_DIR}/luahbtex/lualatex.fmt" ]; then
  mv "${FMT_DIR}/luahbtex/lualatex.fmt" "${FMT_DIR}/luahbtex/luahblatex.fmt"
fi

echo ""
echo "=== Format files ==="
ls -la ${FMT_DIR}/*/*.fmt 2>/dev/null || echo "No format files found!"
echo "=== Done ==="
